---
## ======================================================================
## ANCHORS
## ======================================================================
anchors:
- &slack_alert
  on_failure:
    put: slack-alert
    params:
      text: |
        <((ud/pxf/secrets/ud-concourse-url))/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> went red :blob_slightly_frowning_face:
  on_success:
    put: slack-alert
    params:
      text: |
        <((ud/pxf/secrets/ud-concourse-url))/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> went green! :smile:

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

## ======================================================================
## RESOURCES
## ======================================================================
resources:

- name: pxf-automation-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: automation-dependencies/pxf-automation-dependencies.tar.gz

- name: singlecluster-hdp2
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: singlecluster/HDP2/singlecluster-HDP2.tar.gz

## ---------- Github Repos ----------
- name: pxf_src
  type: git
  icon: git
  source:
    # This pipeline should be using a release tag for running
    # the certification tests, but the Ubuntu test is red on the latest release
    # of PXF (currently 6.2.0) because of an upstream change in
    # greenplum_path.sh. The upstream change only impacts PXF's CI code and
    # not the product's functionality. Until the next release of PXF is tagged
    # this pipeline should be pointed at the master branch and have the pxf_src
    # resource pinned to the commit with the fixed CI code. After the next
    # release, this should be reverted back to using a tag_filter.
    # TODO: revert this change and unpin resouce in UI.
    #tag_filter: release-*
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))

## ---------- Docker Images ----------
- name: gpdb5-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb5-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-rhel8-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-rhel8-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-ubuntu18-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: ccp-7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-public-images/ccp
    tag: latest

## ---------- Greenplum Release Candidate Tarballs ----------
- name: gpdb5_tarball_rhel7
  type: s3
  icon: aws
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/gpdb-stable-builds-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: release_candidates/bin_gpdb_centos7/gpdb5/bin_gpdb.tar.gz

- name: gpdb6_tarball_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz

- name: gpdb6_tarball_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel8_x86_64.tar.gz

- name: gpdb6_ubuntu18_tarball
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-ubuntu18.04_x86_64.tar.gz

## ---------- PXF Released RPM Artifacts ----------
- name: pxf_gp5_rpm_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp5/pxf-gp5-(.*)-1.el7.x86_64.rpm

- name: pxf_gp6_rpm_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1.el7.x86_64.rpm

- name: pxf_gp6_rpm_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1.el8.x86_64.rpm

- name: pxf_gp6_deb_ubuntu18
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1-ubuntu18.04-amd64.deb

- name: slack-alert
  type: slack-notification
  source:
    url: ((ud/pxf/secrets/ud-dev-slack-integration-webhook))

## ======================================================================
## JOBS
## ======================================================================
jobs:

## ---------- Centos 7 Swimlane ----------
- name: Certify GPDB-5 with PXF-GP5 on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb5_tarball_rhel7
      trigger: true
    - get: pxf_package
      resource: pxf_gp5_rpm_rhel7
      trigger: true
    - get: gpdb5-pxf-dev-centos7-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-5 with PXF-GP5-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb5-pxf-dev-centos7-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 5
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-5 with PXF-GP5-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 5
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Certify GPDB-6 with PXF-GP6 on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_tarball_rhel7
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_rpm_rhel7
      trigger: true
    - get: gpdb6-pxf-dev-centos7-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-centos7-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- RHEL 8 Swimlane ----------
- name: Certify GPDB-6 with PXF-GP6 on RHEL8
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_tarball_rhel8
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_rpm_rhel8
      trigger: true
    - get: gpdb6-pxf-dev-rhel8-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on RHEL8
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-rhel8-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on RHEL8
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- Ubuntu 18 Swimlane ----------
- name: Certify GPDB-6 with PXF-GP6 on Ubuntu 18.04
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_ubuntu18_tarball
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_deb_ubuntu18
      trigger: true
    - get: gpdb6-pxf-dev-ubuntu18-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on Ubuntu 18.04
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-ubuntu18-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on Ubuntu 18.04
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- Reporting Gates ----------
- name: Reporting Gate for PXF-GP5
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb5_tarball_rhel7
      passed:
      - Certify GPDB-5 with PXF-GP5 on RHEL7
      trigger: true
    - get: pxf_gp5_rpm_rhel7
      passed:
      - Certify GPDB-5 with PXF-GP5 on RHEL7
      trigger: true
    - get: ccp-7-image
  - task: Print Report for GPDB-5 with PXF-GP5 Artifacts
    <<: *slack_alert
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 5
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Reporting Gate for PXF-GP6
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb6_tarball_rhel7
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL7
      trigger: true
    - get: pxf_gp6_rpm_rhel7
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL7
      trigger: true
    - get: pxf_gp6_rpm_rhel8
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL8
    - get: pxf_gp6_deb_ubuntu18
      passed:
      - Certify GPDB-6 with PXF-GP6 on Ubuntu 18.04
    - get: ccp-7-image
  - task: Print Report for GPDB-6 with PXF-GP6 Artifacts
    <<: *slack_alert
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications
