
## ======================================================================
## ANCHORS
## ======================================================================
pxf_dev_mapr_image_check: &pxf_dev_mapr_image
  - task: check_docker_images_and_tag
    timeout: 30m
    image: gcloud
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))
      GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
      GOOGLE_ZONE: ((ud/pxf/common/google-zone))
      IMAGE_LIST: "gpdb6-centos7-test-pxf-mapr"
    config:
      platform: linux
      inputs:
        - name: pxf_src
      run:
        path: pxf_src/concourse/scripts/check_docker_images_and_tag.bash

## ======================================================================
## RESOURCES
## ======================================================================
resources:
  - name: gcloud
    type: registry-image
    icon: docker
    source:
      repository: google/cloud-sdk
      tag: slim

  - name: pxf-dev-base-cloudbuild-trigger
    type: git
    icon: git
    source:
      branch: ((pxf-git-branch))
      uri: ((ud/pxf/common/git-remote))
      paths:
        - concourse/docker/pxf-dev-base

  - name: dockerfile-gpdb-pxf-mapr
    type: git
    icon: git
    source:
      branch: ((pxf-git-branch))
      uri: ((ud/pxf/common/git-remote))
      paths:
        - concourse/docker/mapr

  - name: base-images-trigger
    type: git
    icon: git
    source:
      uri: ((ud/pxf/common/gp-image-baking-repo-uri))
      branch: ((ud/pxf/common/gp-image-baking-repo-branch))
      private_key: ((ud/pxf/secrets/gp-image-baking-repo-key))
      paths:
        - images/docker/gpdb5/gpdb5-centos7-build-test
        - images/docker/gpdb6/gpdb6-centos7-test
        - images/docker/gpdb6/gpdb6-ubuntu18.04-test
        - images/docker/gpdb6/gpdb6-oel7-test
        - images/docker/gpdb6/gpdb6-rhel8-test
        - images/docker/gpdb7/gpdb7-centos7-test

## ======================================================================
## JOBS
## ======================================================================
jobs:
  - name: Check upstream base images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: gcloud
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
      - get: base-images-trigger
        trigger: true
    - task: trigger_builds
      image: gcloud
      params:
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/google-zone))
        TRIGGER_LIST: "pxf-dev-base rpmrebuild"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/trigger_cloudbuild.bash

  - name: Check pxf-dev-base images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: gcloud
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
        trigger: true
      - get: base-images-trigger
        passed: [Check upstream base images]
        trigger: true
    - task: check_docker_images_and_tag
      timeout: 30m
      image: gcloud
      params:
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/google-zone))
        IMAGE_LIST: "gpdb5-centos7-test-pxf gpdb6-centos7-test-pxf gpdb6-rhel8-test-pxf gpdb6-ubuntu18.04-test-pxf gpdb6-oel7-test-pxf gpdb7-centos7-test-pxf gpdb7-ubuntu18.04-test-pxf"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/check_docker_images_and_tag.bash
    - task: trigger_builds
      image: gcloud
      params:
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/google-zone))
        TRIGGER_LIST: "pxf-dev-server pxf-dev-mapr"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/trigger_cloudbuild.bash

  - name: Check pxf-dev-mapr images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: gcloud
      - get: pxf_src
        resource: dockerfile-gpdb-pxf-mapr
        trigger: true
    - do: *pxf_dev_mapr_image

  - name: Check pxf-dev-mapr images 2
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: gcloud
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
      - get: base-images-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
    - do: *pxf_dev_mapr_image
