## ======================================================================
## ANCHORS
## ======================================================================
ccp_destroy_anchor: &ccp_destroy
  do:
  - put: terraform_gpdb
    resource: terraform
    params:
      action: destroy
      env_name_file: terraform_gpdb/name
      terraform_source: ccp_src/google/
    get_params:
      action: destroy

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:
- name: terraform
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-ud/terraform-resource
    tag: 0.11.15
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
## RESOURCES
## ======================================================================
resources:

- name: every-15mins
  type: time
  icon: clock-outline
  source:
    interval: 15m

- name: terraform
  type: terraform
  icon: tractor
  source:
    env:
      AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/ccp-ci-service-account-key))
    vars:
      project_id: ((ud/pxf/common/google-project-id))
    storage:
      access_key_id: ((tf-machine-access-key-id))
      secret_access_key: ((tf-machine-secret-access-key))
      region_name: ((ud/common/aws-region))
      bucket: ((ud/pxf/common/tf-bucket-name))
      bucket_path: ((tf-bucket-path))

- name: ccp_src
  type: git
  icon: github-circle
  source:
    branch: ((ud/pxf/common/gp-concourse-cluster-provisioner-git-branch))
    private_key: ((gp-concourse-cluster-provisioner-git-key))
    uri: ((ud/pxf/common/gp-concourse-cluster-provisioner-git-remote))

- name: ccp-7
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-public-images/ccp
    tag: latest

- name: gpdb6-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6_rhel7_rpm_latest-0
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: latest-0_gpdb6/greenplum-db-(.*)-rhel7-x86_64.rpm

- name: pxf_src_tag
  type: git
  icon: github-circle
  source:
    branch: master
    uri: ((ud/pxf/common/git-remote))
    tag_filter: ((pxf-tag))

- name: pxf_src
  type: git
  icon: github-circle
  source:
    branch: ((ud/pxf/prod/git-branch))
    uri: ((ud/pxf/common/git-remote))

- name: pxf_tarball
  type: s3
  icon: archive
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/longevity/((pxf-tag))/pxf-gp6.el7.tar.gz

- name: cluster_env_files_tar
  type: s3
  icon: archive
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/longevity/((pxf-tag))/cluster_env_files.tar.gz

- name: dataproc_env_files_tar
  type: s3
  icon: archive
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/longevity/((pxf-tag))/dataproc_env_files.tar.gz

- name: dataproc_2_env_files_tar
  type: s3
  icon: archive
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/longevity/((pxf-tag))/dataproc_2_env_files.tar.gz

- name: singlecluster-hdp2
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: singlecluster/HDP2/singlecluster-HDP2.tar.gz

- name: pxf-automation-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: automation-dependencies/pxf-automation-dependencies.tar.gz

## ======================================================================
## JOBS
## ======================================================================
jobs:

- name: compile_pxf_((pxf-tag))
  plan:
  - in_parallel:
    - get: pxf_src
      resource: pxf_src_tag
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
    - get: gpdb6-pxf-dev-centos7-image
  - task: compile_pxf
    image: gpdb6-pxf-dev-centos7-image
    file: pxf_src/concourse/tasks/build.yml
  - put: pxf_tarball
    params:
      file: dist/pxf-gp6-*.el7.tar.gz

- name: provision_clusters_((pxf-tag))
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: ccp_src
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
    - get: pxf_src
    - get: pxf_tarball
      passed:
      - compile_pxf_((pxf-tag))
      trigger: true
    - get: ccp-7
    - get: gpdb6-pxf-dev-centos7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - in_parallel:
    - do:
      - put: terraform_gpdb
        resource: terraform
        params:
          action: create
          delete_on_failure: true
          generate_random_name: true
          terraform_source: ccp_src/google/
          vars:
            PLATFORM: centos7
            number_of_nodes: ((number_of_gpdb_nodes))
            extra_nodes: 1
            segments_per_host: 4
            instance_type: n1-standard-4
            ccp_reap_minutes: 262800
      - task: Generate Greenplum Cluster
        input_mapping:
          gpdb_rpm: gpdb_package
          terraform: terraform_gpdb
        file: ccp_src/ci/tasks/gen_cluster.yml
        image: ccp-7
        params:
          AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
          AWS_DEFAULT_REGION: ((ud/common/aws-region))
          BUCKET_PATH: ((tf-bucket-path))
          BUCKET_NAME: ((ud/pxf/common/tf-bucket-name))
          PLATFORM: centos7
          CLOUD_PROVIDER: google
          GPDB_RPM: true
      - in_parallel:
        - task: Initialize Greenplum
          file: ccp_src/ci/tasks/gpinitsystem.yml
        - task: Install Hadoop
          file: pxf_src/concourse/tasks/install_hadoop.yml
          image: gpdb6-pxf-dev-centos7-image
          params:
            ACCESS_KEY_ID: ((tf-machine-access-key-id))
            SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
            IMPERSONATION: ((enable-impersonation-multinode))
    - task: Generate Hadoop Cluster 1
      file: pxf_src/concourse/tasks/install_dataproc.yml
      params:
        CLUSTER_NAME: pxf-((pxf-tag))-longevity-1
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/ccp-ci-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/google-zone))
        IMAGE_VERSION: ((dataproc-image-version))
        KERBEROS: ((kerberos-enabled))
        ccp_reap_minutes: 20160
    - task: Generate Hadoop Cluster 2
      file: pxf_src/concourse/tasks/install_dataproc.yml
      output_mapping:
        dataproc_env_files: dataproc_2_env_files
      params:
        CLUSTER_NAME: pxf-((pxf-tag))-longevity-2
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/kerberos-ccp-ci-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/kerberos-google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/kerberos-google-zone))
        HADOOP_USER: gpuser
        IMAGE_VERSION: ((dataproc-image-version))
        INITIALIZATION_SCRIPT: gs://data-gpdb-ud-kerberos-scripts/scripts/initialization-for-kerberos.sh
        INSTANCE_TAGS: bosh-network,data-gpdb-ud-access
        KERBEROS: ((kerberos-enabled))
        KEY: dataproc-kerberos-key
        KEYRING: dataproc-kerberos
        ccp_reap_minutes: 20160
        NO_ADDRESS: false
        PROXY_USER: gpuser
        SECRETS_BUCKET: ((ud/pxf/secrets/kerberos-pxf-secrets-bucket-name))
  - task: Setup PXF
    input_mapping:
      terraform: terraform_gpdb
    file: pxf_src/concourse/tasks/install_pxf_on_ccp.yml
    image: ccp-7
    params:
      AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
      AWS_DEFAULT_REGION: ((ud/common/aws-region))
      BUCKET_PATH: ((tf-bucket-path))
      BUCKET_NAME: ((ud/pxf/common/tf-bucket-name))
      CLOUD_PROVIDER: google
      GP_VER: 6
      IMPERSONATION: ((enable-impersonation-multinode))
      INSTALL_GPHDFS: false
      KERBEROS: ((kerberos-enabled))
      PLATFORM: centos7
      PXF_JVM_OPTS: ((pxf-jvm-opts))
  - in_parallel:
    - do:
      - task: Archive Cluster Configs
        file: pxf_src/concourse/tasks/archive_directory.yml
        image: ccp-7
        input_mapping:
          in_dir: cluster_env_files
        output_mapping:
          out_dir: archive
        params:
          name: cluster_env_files
      - put: cluster_env_files_tar
        params:
          file: archive/cluster_env_files.tar.gz
    - do:
      - task: Archive Dataproc Configs
        file: pxf_src/concourse/tasks/archive_directory.yml
        image: ccp-7
        input_mapping:
          in_dir: dataproc_env_files
        output_mapping:
          out_dir: archive
        params:
          name: dataproc_env_files
      - put: dataproc_env_files_tar
        params:
          file: archive/dataproc_env_files.tar.gz
    - do:
      - task: Archive Dataproc-2 Configs
        file: pxf_src/concourse/tasks/archive_directory.yml
        image: ccp-7
        input_mapping:
          in_dir: dataproc_2_env_files
        output_mapping:
          out_dir: archive
        params:
          name: dataproc_2_env_files
      - put: dataproc_2_env_files_tar
        params:
          file: archive/dataproc_2_env_files.tar.gz

- name: longevity_test_((pxf-tag))
  plan:
  - get: every-15mins
    trigger: true
  - in_parallel:
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
      - provision_clusters_((pxf-tag))
    - get: pxf_src
      passed:
      - provision_clusters_((pxf-tag))
    - get: pxf_tarball
      passed:
      - provision_clusters_((pxf-tag))
    - get: cluster_env_files
      resource: cluster_env_files_tar
      passed:
      - provision_clusters_((pxf-tag))
      params:
        unpack: true
    - get: dataproc_env_files
      resource: dataproc_env_files_tar
      passed:
      - provision_clusters_((pxf-tag))
      params:
        unpack: true
    - get: dataproc_2_env_files
      resource: dataproc_2_env_files_tar
      passed:
      - provision_clusters_((pxf-tag))
      params:
        unpack: true
    - get: gpdb6-pxf-dev-centos7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Longevity Test PXF Multinode
    input_mapping:
      bin_gpdb: gpdb_binary
    image: gpdb6-pxf-dev-centos7-image
    file: pxf_src/concourse/tasks/test_pxf_on_ccp.yml
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
      HIVE_VERSION: 2
      IMPERSONATION: ((enable-impersonation-multinode))
      KERBEROS: ((kerberos-enabled))
      GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
      GP_VER: 6
      GROUP: multiClusterSecurity
      PXF_JVM_OPTS: ((pxf-jvm-opts))
