---
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: gpdb_src
  type: git
  source:
    branch: ((gpdb-git-branch))
    uri: ((gpdb-git-remote))

- name: gpdb_pxf_trigger
  type: git
  source:
    branch: ((gpdb-branch))
    uri: ((ud/pxf/common/gpdb-git-remote))
    paths:
    - gpcontrib/pxf_fdw
    - src/backend/foreign
    - src/backend/commands/copy.c
    - src/include/commands/copy.h
    - src/include/catalog/pg_foreign_server.h
    - src/include/catalog/pg_foreign_data_wrapper.h
    - src/backend/executor/nodeForeignscan.c
    - src/include/executor/nodeForeignscan.h

- name: pxf_src
  type: git
  source:
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))
    private_key: ((gp-concourse-cluster-provisioner-git-key))

- name: gpdb-pxf-dev-centos7
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-centos7-build
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-centos7-build
    tag: latest

- name: gpdb-pxf-dev-centos7-hdp2-server
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

# ~/workspace/gp-continuous-integration/secrets/gpdb6-integration-testing.dev.yml
- name: libquicklz-centos7
  type: gcs
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-dev-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/libquicklz-(\d.*)\.el7\.x86_64\.rpm

- name: libquicklz-devel-centos7
  type: gcs
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-dev-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/libquicklz-devel-(\d.*)\.el7\.x86_64\.rpm

- name: libsigar-centos7
  type: gcs
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-dev-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: gp-internal-artifacts/centos7/sigar-rhel7_x86_64-(.*)\.targz

- name: pxf_tarball
  type: s3
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/((folder-prefix))_((gpdb-branch))/latest/pxf.tar.gz

- name: bin_gpdb
  type: s3
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/aws-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: pxf_artifacts/((folder-prefix))_((gpdb-branch))/latest/bin_gpdb.tar.gz

jobs:

- name: compile_pxf
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_src
    - get: gpdb_pxf_trigger
      trigger: true
    - get: gpdb-pxf-dev-centos7
  - task: compile_pxf
    image: gpdb-pxf-dev-centos7
    file: pxf_src/concourse/tasks/compile_pxf.yml
  - put: pxf_tarball
    params: {file: pxf_artifacts/pxf.tar.gz}

- name: compile_gpdb
  plan:
  - in_parallel:
    - get: gpdb_src
      params: {submodules: all, submodules_recursive: true}
      trigger: true
    - get: gpdb6-centos7-build
    - get: libquicklz-installer
      resource: libquicklz-centos7
    - get: libquicklz-devel-installer
      resource: libquicklz-devel-centos7
    - get: libsigar-installer
      resource: libsigar-centos7
  - task: compile_gpdb_centos7
    file: gpdb_src/concourse/tasks/compile_gpdb.yml
    image: gpdb6-centos7-build
    params:
      BLD_TARGETS: "clients loaders"
      CONFIGURE_FLAGS: '--enable-cassert --enable-debug-extensions'
      TARGET_OS: centos
      TARGET_OS_VERSION: 7
    timeout: 30m
  - put: bin_gpdb
    params: {file: gpdb_artifacts/bin_gpdb.tar.gz}

- name: test_pxf
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: bin_gpdb
      - name: pxf_src
      - name: pxf_tarball
      params:
        GROUP: fdw_smoke_schedule
        HADOOP_CLIENT: HDP
        IMPERSONATION: true
        PGPORT: ((pgport))
        PG_REGRESS: true
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_s3
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: bin_gpdb
      - name: pxf_src
      - name: pxf_tarball
      params:
        ACCESS_KEY_ID: ((tf-machine-access-key-id))
        GROUP: fdw_hcfs_schedule
        HADOOP_CLIENT: HDP
        IMPERSONATION: true
        PGPORT: ((pgport))
        PG_REGRESS: true
        PROTOCOL: s3
        SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_gcs
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: bin_gpdb
      - name: pxf_src
      - name: pxf_tarball
      params:
        ACCESS_KEY_ID: ((tf-machine-access-key-id))
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/gsc-ci-service-account-key))
        GROUP: fdw_hcfs_schedule
        HADOOP_CLIENT: HDP
        IMPERSONATION: true
        PGPORT: ((pgport))
        PG_REGRESS: true
        PROTOCOL: gs
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_wasbs
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: bin_gpdb
      - name: pxf_src
      - name: pxf_tarball
      params:
        ACCESS_KEY_ID: ((tf-machine-access-key-id))
        GROUP: fdw_hcfs_schedule
        HADOOP_CLIENT: HDP
        IMPERSONATION: true
        PGPORT: ((pgport))
        PG_REGRESS: true
        PROTOCOL: wasbs
        WASBS_ACCOUNT_KEY: ((ud/pxf/secrets/wasb-account-key))
        WASBS_ACCOUNT_NAME: ((ud/pxf/common/wasb-account-name))
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_adl
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: bin_gpdb
      - name: pxf_src
      - name: pxf_tarball
      params:
        ADL_ACCOUNT: ((ud/pxf/common/adl-account))
        ADL_OAUTH2_CLIENT_ID: ((ud/pxf/secrets/adl-client-id))
        ADL_OAUTH2_CREDENTIAL: ((ud/pxf/secrets/adl-credential))
        ADL_OAUTH2_REFRESH_URL: ((ud/pxf/common/adl-refresh-url))
        GROUP: fdw_hcfs_schedule
        HADOOP_CLIENT: HDP
        IMPERSONATION: true
        PGPORT: ((pgport))
        PG_REGRESS: true
        PROTOCOL: adl
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash

- name: test_pxf_minio
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: bin_gpdb
      passed:
      - compile_gpdb
      trigger: true
    - get: gpdb_src
      passed:
      - compile_pxf
      - compile_gpdb
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    file: pxf_src/concourse/tasks/test_pxf.yml
    image: gpdb-pxf-dev-centos7-hdp2-server
    params:
      GROUP: fdw_hcfs_schedule
      IMPERSONATION: false
      PGPORT: ((pgport))
      PG_REGRESS: true
      PROTOCOL: minio
