---
{# change num_versions manually to download more Greenplum versions #}
{% set num_versions = num_gpdb5_versions %}
{% if gpdb_type == '6X_STABLE' %}
  {% set num_versions = num_gpdb6_versions %}
{% endif %}
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: pxf_src
  type: git
  icon: git
  source:
    branch: ((ud/pxf/prod/git-branch))
    uri: ((pxf-git-remote))
    private_key: ((ccp-git-key))

- name: gpdb-pxf-dev-centos6-hdp2-server
  type: registry-image
  icon: docker
  source:
{% if gpdb_type == "6X_STABLE" %}
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos6-test-pxf-hdp2
{% else %}
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb5-centos6-test-pxf-hdp2
{% endif %}
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/gsc-ci-service-account-key))

    - name: gpdb-pxf-dev-centos7-hdp2-server
  type: registry-image
  icon: docker
  source:
{% if gpdb_type == "6X_STABLE" %}
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2
{% else %}
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb5-centos7-test-pxf-hdp2
{% endif %}
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/gsc-ci-service-account-key))
{% if gpdb_type == "6X_STABLE" %}

- name: gpdb-pxf-dev-ubuntu18-hdp2-server
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf-hdp2
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/gsc-ci-service-account-key))
{% endif %}

{% for version in range(num_versions) %}
- name: gpdb_rhel6_rpm_latest-[[ version ]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
{% if gpdb_type == "5X_STABLE" %}
    regexp: latest-[[ version ]]_gpdb5/greenplum-db-(.*)-rhel6-x86_64.rpm
{% else %}
    regexp: latest-[[ version ]]_gpdb6/greenplum-db-(.*)-rhel6-x86_64.rpm
{% endif %}

- name: gpdb_rhel7_rpm_latest-[[ version ]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
{% if gpdb_type == "5X_STABLE" %}
    regexp: latest-[[ version ]]_gpdb5/greenplum-db-(.*)-rhel7-x86_64.rpm
{% else %}
    regexp: latest-[[ version ]]_gpdb6/greenplum-db-(.*)-rhel7-x86_64.rpm
{% endif %}
{% if gpdb_type == "6X_STABLE" %}
- name: gpdb_ubuntu18_deb_latest-[[ version ]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
    regexp: latest-[[ version ]]_gpdb6/greenplum-db-(.*)-ubuntu18.04-amd64.deb

{% endif %}
{% endfor %}

- name: pxf_tarball_gpdb6_rhel6
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
    versioned_file: prod/snapshots/pxf6/pxf-gpdb6-SNAPSHOT-rhel6-x86_64.tar.gz

- name: pxf_tarball_gpdb6_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
    versioned_file: prod/snapshots/pxf6/pxf-gpdb6-SNAPSHOT-rhel7-x86_64.tar.gz

- name: pxf_tarball_gpdb6_ubuntu18
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/gsc-ci-service-account-key))
    versioned_file: prod/snapshots/pxf6/pxf-gpdb6-SNAPSHOT-ubuntu18.04-x86_64.tar.gz

## ======================================================================
## ANCHORS
## ======================================================================

anchors:
- &run_anchor
  run:
    path: sh
    args:
    - -exc
    - |
        limits='gpadmin soft core unlimited\ngpadmin soft nproc 131072\ngpadmin soft nofile 65536'
        echo -e "${limits}" >> /etc/security/limits.d/gpadmin-limits.conf
        export GROUP=HdfsSmokeTest,WritableSmokeTest "PATH=${PWD}/pxf_src/concourse/scripts:${PATH}" &&
        export PXF_SRC="${PWD}/pxf_src" &&
        install_gpdb.bash &&
        su gpadmin "$(command -v initialize_gpdb.bash)" &&
        pgregress_pxf.bash

## ======================================================================
## JOBS
## ======================================================================

jobs:
- name: Test PXF-GP6 Backward Compatibility on RHEL6
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: pxf_tarball
      resource: pxf_tarball_gpdb6_rhel6
      trigger: true
    - get: gpdb-pxf-dev-centos6-hdp2-server
{% for version in range(num_versions) %}
    - get: gpdb_package_latest-[[ version ]]
      resource: gpdb_rhel6_rpm_latest-[[ version ]]
{% endfor %}
{% for version in range(num_versions) %}
  - task: Test Against Greenplum Latest - [[ version ]] RHEL6
    image: gpdb-pxf-dev-centos6-hdp2-server
    config:
      platform: linux
      <<: *run_anchor
      inputs:
      - name: pxf_src
      - name: pxf_tarball
      - name: gpdb_package_latest-[[ version ]]
      params:
        GPDB_PKG_DIR: gpdb_package_latest-[[ version ]]
{% endfor %}

- name: Test PXF-GP6 Backward Compatibility on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: pxf_tarball
      resource: pxf_tarball_gpdb6_rhel7
      trigger: true
    - get: gpdb-pxf-dev-centos7-hdp2-server
{% for version in range(num_versions) %}
    - get: gpdb_package_latest-[[ version ]]
      resource: gpdb_rhel7_rpm_latest-[[ version ]]
{% endfor %}
{% for version in range(num_versions) %}
  - task: Test Against Greenplum Latest - [[ version ]] RHEL7
    image: gpdb-pxf-dev-centos7-hdp2-server
    config:
      platform: linux
      <<: *run_anchor
      inputs:
      - name: pxf_src
      - name: pxf_tarball
      - name: gpdb_package_latest-[[ version ]]
      params:
        GPDB_PKG_DIR: gpdb_package_latest-[[ version ]]
{% endfor %}
{% if gpdb_type == "6X_STABLE" %}

- name: Test PXF-GP6 Backward Compatibility on Ubuntu18
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: pxf_tarball
      resource: pxf_tarball_gpdb6_ubuntu18
      trigger: true
    - get: gpdb-pxf-dev-ubuntu18-hdp2-server
{% for version in range(num_versions) %}
    - get: gpdb_package_latest-[[ version ]]
      resource: gpdb_ubuntu18_deb_latest-[[ version ]]
{% endfor %}
{% for version in range(num_versions) %}
  - task: Test Against Greenplum Latest - [[ version ]] Ubuntu18
    image: gpdb-pxf-dev-ubuntu18-hdp2-server
    config:
      platform: linux
      <<: *run_anchor
      inputs:
      - name: pxf_src
      - name: pxf_tarball
      - name: gpdb_package_latest-[[ version ]]
      params:
        GPDB_PKG_DIR: gpdb_package_latest-[[ version ]]
{% endfor %}
{% endif %}
