---
{% set attempts = 3 %}
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: twice-a-day
  type: time
  icon: clock-outline
  source:
    interval: 12h

- name: pxf_src
  type: git
  icon: git
  source:
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))

- name: ubuntu18
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-build
    tag: latest

- name: pivnet_cli
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: pivotal-cf/pivnet-cli/pivnet

{% for i in range(num_gpdb5_versions) %}
- name: gpdb5_rhel7_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb5/greenplum-db-(.*)-rhel7-x86_64.rpm

{% endfor %}
{% for i in range(num_gpdb6_versions) %}
- name: gpdb6_rhel7_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb6/greenplum-db-(.*)-rhel7-x86_64.rpm

- name: gpdb6_rhel8_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb6/greenplum-db-(.*)-rhel8-x86_64.rpm

- name: gpdb6_ubuntu18_deb_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/pivnet-artifacts-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb6/greenplum-db-(.*)-ubuntu18.04-amd64.deb
{% endfor %}

jobs:
- name: Download Latest PivNet CLI
  plan:
  - in_parallel:
    - get: twice-a-day
      trigger: true
    - get: pxf_src
    - get: ubuntu18
    - get: pivnet_cli
  - task: Get Latest PivNet CLI
    attempts: [[attempts]]
    image: ubuntu18
    config:
      platform: linux
      inputs:
        - name: pxf_src
        - name: pivnet_cli
      outputs:
        - name: pivnet_cli
      params:
        PIVNET_CLI_DIR: pivnet_cli
      run:
        path: pxf_src/concourse/scripts/download_pivnet_cli.bash
  - put: pivnet_cli
    params:
      file: pivnet_cli/pivnet

- name: Get Greenplum Product Files GP5
  plan:
  - in_parallel:
    - get: pxf_src
      passed: [Download Latest PivNet CLI]
    - get: ubuntu18
    - get: pivnet_cli
      passed: [Download Latest PivNet CLI]
      trigger: true
{% for i in range(num_gpdb5_versions) %}
    - get: gpdb5_rhel7_rpm_latest-[[i]]
{% endfor %}
{% for i in range(num_gpdb5_versions - 1, -1, -1) %}
  - task: Get Greenplum Product Files GP5 Latest - [[i]]
    attempts: [[attempts]]
    # this task will fail on centos6
    image: ubuntu18
    config:
      platform: linux
      inputs:
        - name: pxf_src
        - name: pivnet_cli
        - name: gpdb5_rhel7_rpm_latest-[[i]]
        {% if i > 0 %}
        # save a download from pivnet if not fetching latest
        - name: gpdb5_rhel7_rpm_latest-[[i - 1]]
        {% endif %}
      outputs:
        - name: gpdb5_rhel7_rpm_latest-[[i]]
      params:
        GPDB_VERSION: 5
        LIST_OF_DIRS: gpdb5_rhel7_rpm_latest-[[i]]
        LIST_OF_PRODUCTS: greenplum-db-GPDB_VERSION-rhel7-x86_64.rpm
        PIVNET_API_TOKEN: ((ud/pxf/secrets/pivnet-uaa-refresh-token))
        PIVNET_CLI_DIR: pivnet_cli
        PRODUCT_SLUG: pivotal-gpdb
        VERSIONS_BEFORE_LATEST: [[i]]
      run:
        path: pxf_src/concourse/scripts/get_product_files.bash
  - put: gpdb5_rhel7_rpm_latest-[[i]]
    params:
      file: gpdb5_rhel7_rpm_latest-[[i]]/greenplum-db-5.*-rhel7-x86_64.rpm
{% endfor %}

- name: Get Greenplum Product Files GP6
  plan:
  - in_parallel:
    - get: pxf_src
      passed: [Download Latest PivNet CLI]
    - get: ubuntu18
    - get: pivnet_cli
      passed: [Download Latest PivNet CLI]
      trigger: true
{% for i in range(num_gpdb6_versions) %}
    - get: gpdb6_rhel7_rpm_latest-[[i]]
    - get: gpdb6_rhel8_rpm_latest-[[i]]
    - get: gpdb6_ubuntu18_deb_latest-[[i]]
{% endfor %}
{% for i in range(num_gpdb6_versions - 1, -1, -1) %}
  - task: Get Greenplum Product Files GP6 Latest - [[i]]
    attempts: [[attempts]]
    # this task will fail on centos6
    image: ubuntu18
    config:
      platform: linux
      inputs:
        - name: pxf_src
        - name: pivnet_cli
        - name: gpdb6_rhel7_rpm_latest-[[i]]
        - name: gpdb6_rhel8_rpm_latest-[[i]]
        - name: gpdb6_ubuntu18_deb_latest-[[i]]
        {% if i > 0 %}
        # save a download from pivnet if not fetching latest
        - name: gpdb6_rhel7_rpm_latest-[[i - 1]]
        - name: gpdb6_rhel8_rpm_latest-[[i - 1]]
        - name: gpdb6_ubuntu18_deb_latest-[[i - 1]]
        {% endif %}
      outputs:
        - name: gpdb6_rhel7_rpm_latest-[[i]]
        - name: gpdb6_rhel8_rpm_latest-[[i]]
        - name: gpdb6_ubuntu18_deb_latest-[[i]]
      params:
        GPDB_VERSION: 6
        LIST_OF_DIRS: gpdb6_rhel7_rpm_latest-[[i]],gpdb6_rhel8_rpm_latest-[[i]],gpdb6_ubuntu18_deb_latest-[[i]]
        LIST_OF_PRODUCTS: greenplum-db-GPDB_VERSION-rhel7-x86_64.rpm,greenplum-db-GPDB_VERSION-rhel8-x86_64.rpm,greenplum-db-GPDB_VERSION-ubuntu18.04-amd64.deb
        PIVNET_API_TOKEN: ((ud/pxf/secrets/pivnet-uaa-refresh-token))
        PIVNET_CLI_DIR: pivnet_cli
        PRODUCT_SLUG: pivotal-gpdb
        VERSIONS_BEFORE_LATEST: [[i]]
      run:
        path: pxf_src/concourse/scripts/get_product_files.bash
  - put: gpdb6_rhel7_rpm_latest-[[i]]
    params:
      file: gpdb6_rhel7_rpm_latest-[[i]]/greenplum-db-6.*-rhel7-x86_64.rpm
  - put: gpdb6_rhel8_rpm_latest-[[i]]
    params:
      file: gpdb6_rhel8_rpm_latest-[[i]]/greenplum-db-6.*-rhel8-x86_64.rpm
  - put: gpdb6_ubuntu18_deb_latest-[[i]]
    params:
      file: gpdb6_ubuntu18_deb_latest-[[i]]/greenplum-db-6.*-ubuntu18.04-amd64.deb
{% endfor %}
