-- start_ignore
-- end_ignore
-- @description query01 for PXF test for cloud access where no server and no credentials are specified running alongside an HDFS setup
--
-- start_matchsubs
--
-- # create a match/subs
--
-- m/HINT:  Ensure that.*/
-- s|HINT:  Ensure that.*|HINT:  Ensure that 'server-dir' includes only the configuration files for profile 's3a'. Check the PXF logs located in the 'logs-dir' directory on host 'mdw' or 'set client_min_messages=LOG' for additional details.|
--
-- m/DETAIL/
-- s/DETAIL/CONTEXT/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- m/pxf:\/\/(.*)\/pxf_automation_data/
-- s/pxf:\/\/.*PROFILE=s3:text&.*/pxf:\/\/pxf_automation_data?PROFILE=s3:text&ACCESS_AND_SECRET_KEY/
--
-- end_matchsubs

SELECT *  FROM cloudaccess_no_server_credentials_no_config_with_hdfs;
