---
- name: Install IPA client packages
  ansible.builtin.yum:
    name: ['bind-utils', 'ipa-client', 'ipa-admintools', 'openldap-clients']
    state: present
    update_cache: true
    lock_timeout: 300

- name: Run IPA client installer
  ansible.builtin.shell:
    cmd: "ipa-client-install --principal admin --unattended --server ccp-{{ cluster_name }}-ipa.{{ ansible_domain }} --domain {{ ansible_domain }} --password {{ ipa_password }}"
    creates: /var/log/ipaclient-install.log
