-- start_ignore
-- end_ignore
-- @description query01 for PXF test for cloud access where server is specified but credentials are not specified and no configuration file exists for the specified server
--
-- start_matchsubs
--
-- # create a match/subs
--
-- m/PXF server error.*(com.amazonaws.AmazonClientException: No AWS Credentials provided by BasicAWSCredentialsProvider).*/
-- s/PXF server error.*/PXF server error : com.amazonaws.AmazonClientException: No AWS Credentials provided by BasicAWSCredentialsProvider/
--
-- m/DETAIL/
-- s/DETAIL/CONTEXT/
--
-- m/pxf:\/\/(.*)\/pxf_automation_data/
-- s/pxf:\/\/.*PROFILE/pxf:\/\/pxf_automation_data?PROFILE/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- end_matchsubs

SELECT *  FROM cloudaccess_server_no_credentials_no_config;
